#/usr/bin/env bash

# exit on failure
set -e
# echo commands as they are run
set -o verbose

THIS_DIR="$( dirname "${BASH_SOURCE[0]}" )"

SRC_ROOT=$SRC_ROOT/$LIBSBML_NAME
INSTALL_NAME="$LIBSBML_INSTALL_DIR"
BUILD_DIR="$BUILD_ROOT/$LIBSBML_NAME-$PLATFORM"

LIBSBMLNS=OFF
BUILD_TYPE=Release

echo "*** using build dir ***"
echo $BUILD_DIR
rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR
cd $BUILD_DIR
"$CMAKE" "$CMAKE_GEN" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX="$INSTALL_NAME" -DLIBBZ_LIBRARY="$LIBBZIP2" -DLIBBZ_INCLUDE_DIR="$LIBBZIP2_INCLUDE" -DLIBXML_LIBRARY="$LIBXML2" -DLIBXML_INCLUDE_DIR="$LIBXML2_INCLUDE" -DLIBZ_LIBRARY="$ZLIB" -DLIBZ_INCLUDE_DIR="$ZLIB_INCLUDE" $CMAKE_ICONV_FLAGS -DENABLE_ARRAYS=OFF -DENABLE_COMP=ON -DENABLE_DISTRIB=ON -DENABLE_DYN=ON -DENABLE_FBC=ON -DENABLE_GROUPS=ON -DENABLE_LAYOUT=ON -DENABLE_MULTI=OFF -DENABLE_QUAL=ON -DENABLE_RENDER=ON -DENABLE_REQUIREDELEMENTS=ON -DENABLE_SPATIAL=OFF -DWITH_CPP_NAMESPACE="$LIBSBMLNS" -DLIBSBML_USE_LEGACY_MATH=ON $SRC_ROOT
eval $CMAKE_BUILD_CMD
